---
version: 2
plan:
  project-key: GDPR
  key: GDPRBUILD
  name: GDPR

triggers:
  - polling: 130

variables:
  release_version: patch

stages:
  - Build:
      jobs:
        - Build
  - Release:
      manual: true
      jobs:
        - Release

Build:
  key: BD
  tasks:
    - clean
    - script: |
        #!/usr/env/bin bash
        set -e
        docker-compose -f test/docker-compose.yml up --exit-code-from tests
        /opt/scripts/docker/stop-docker-containers.sh
  requirements:
    - REMOTE_ONLY

Release:
  key: REL
  tasks:
    - clean
    - script: |
        #!/usr/env/bin bash
        /opt/scripts/git/git-repository-information-restore.sh
        docker run -e GIT_REPO=${bamboo_repository_git_repositoryUrl} -e RELEASE_VERSION=${bamboo.release_version} acd-docker.repository.milieuinfo.be/milieuinfo/wc-release:1.0.0
        /opt/scripts/docker/stop-docker-containers.sh
  requirements:
    - REMOTE_ONLY

---
version: 2
plan:
  key: GDPRBUILD

plan-permissions:
  - groups:
      - bamboo-admin
      - bamboo-release
      - developer-admin
    permissions:
      - view
      - edit
      - build
      - clone
      - admin
